### ISSUE TITLE
stat 함수 조사

### ISSUE THREAD

**Issue by thsgustlr0318** [luxlunae15/SE_project2#3]
stat 함수 조사

**Comment by thsgustlr0318** [comment]
stat함수는 파일의 정보를 읽어오는 함수이다.
함수의 인자는 다음과 같다.

struct stat {     dev_t           st_dev;        /*ID of device containing file */     ino_t            st_ino;          /*inode number*/     mode_t       st_mode;     /*protection*/     nlink_t         st_nlink;       /*number of hard links*/     uid_t            st_uid;          /*user ID of owner*/     gid_t            st_gid;          /*group ID of owner*/     dev_t           st_rdev;        /*device ID (if special file)*/     off_t             st_size;         /*total size, in byte*/     blksize_t      st_blksize;    /*blocksize for file system I/O*/     blkcnt_t       st_blocks;     /*number of 512B blocks allocated*/     time_t;        st_atime;      /*time of last access*/     time_t;        st_mtime;     /*time of last modification*/     time_t         st_xtime;       /*time of last status change*/};
--

**Comment by luxlunae15** [comment]
가독성이 떨어집니다
